# Generated by Django 5.1.2 on 2024-10-09 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_hospital_alter_user_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicalhistory',
            options={'verbose_name': 'Medical History', 'verbose_name_plural': 'Medical Histories'},
        ),
    ]
