# Generated by Django 5.1.2 on 2024-10-09 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_medicalhistory_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='core.hospital'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('Doctor', 'Doctor'), ('Admin', 'Admin')], max_length=6, null=True),
        ),
    ]
